### ISSUE TITLE
Using LAME::Encoder with 24 bits per sample .wav input files?

### ISSUE THREAD

**Issue by richorton** [rdvdijk/lame#2]
Hi All,

Is there any way to provide the native LAME configuration option for the "bitwidth" using this gem?

I'm having an issue whereby I need to encode 24 bit .wav files to 192/320 MP3's through my application. So far I am struggling as the WaveFile gem (which is used in the encoding_spec.rb example) only supports 8, 16 and 32 bit files.

Upon researching the problem I have discovered that LAME has a "--bitwidth" flag that can be specified as part of the configuration, but I can't see any example of that flag in this implementation of LAME?

I'd be very grateful if anyone has any info!

Thanks.

**Comment by rdvdijk** [comment]
Hi Rich,

I've finally released a new version of the gem. I've also added two examples for encoding 24-bit files in the [`spec/integration/encoding_spec.rb`](https://github.com/rdvdijk/lame/blob/master/spec/integration/encoding_spec.rb). 
- One method uses the `encode_long` method, where you need to scale the input values to the proper maximum `long` value (which is dependent on your system's architecture).
- The other method uses the `encode_float` method, where you need to scale the input values to values between -1.0 and +1.0 (which is a bit easier than the first method). 

Both these methods actually didn't work in version 0.0.3, but I had never noticed because I never added a test for 24-bit audio.
